# Generated by Django 2.1.5 on 2021-08-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.CharField(blank=True, max_length=128, primary_key=True, serialize=False),
        ),
    ]
